# Generated by Django 3.1.5 on 2021-07-13 08:16

import Restaurant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalyrs', models.CharField(blank=True, max_length=50, null=True)),
                ('billnum', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bill_date', models.CharField(max_length=50, null=True)),
                ('table', models.CharField(blank=True, max_length=50, null=True)),
                ('amnt', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('taxable_amnt', models.FloatField(blank=True, null=True)),
                ('tax_amnt', models.FloatField(blank=True, null=True)),
                ('total_amnt', models.FloatField(blank=True, null=True)),
                ('billprt', models.IntegerField(blank=True, null=True)),
                ('billactive', models.IntegerField(blank=True, null=True)),
                ('bill_time', models.TimeField(auto_now=True, null=True)),
                ('billuser', models.CharField(blank=True, max_length=64, null=True)),
                ('is_realtime', models.BooleanField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('billid', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CBMSdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbmsusername', models.CharField(max_length=64, null=True)),
                ('cbmspassword', models.CharField(max_length=64, null=True)),
                ('sellerpan', models.CharField(blank=True, max_length=9, null=True)),
                ('fiscalyear', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='masterPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('image', models.ImageField(blank=True, null=True, upload_to='CategoryMenu/')),
            ],
        ),
        migrations.CreateModel(
            name='RestoLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datentime', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('activity', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('occupied', models.IntegerField(blank=True, null=True)),
                ('occHrs', models.IntegerField(blank=True, null=True)),
                ('occMin', models.IntegerField(blank=True, null=True)),
                ('reserved', models.IntegerField(blank=True, null=True)),
                ('merged', models.IntegerField(blank=True, null=True)),
                ('disval', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalServedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='User/')),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('printsts', models.BooleanField(blank=True, null=True)),
                ('servests', models.BooleanField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menu')),
                ('orderedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.table')),
            ],
        ),
        migrations.CreateModel(
            name='MergeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table1', to='Restaurant.table')),
                ('table2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table2', to='Restaurant.table')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menucategory'),
        ),
        migrations.CreateModel(
            name='BillSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_ird', models.BooleanField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.bill')),
            ],
        ),
    ]
