# Generated by Django 3.0.2 on 2020-02-17 05:47

import Restaurant.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
                ('image', models.ImageField(blank=True, null=True, upload_to='CategoryMenu/')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Menu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Table')),
            ],
        ),
        migrations.CreateModel(
            name='MenuInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Inventory')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.MenuCategory'),
        ),
    ]
