# Generated by Django 3.0.4 on 2020-04-02 12:59

import Restaurant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalyrs', models.CharField(blank=True, max_length=50, null=True)),
                ('billnum', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_date', models.CharField(max_length=50, null=True)),
                ('table', models.CharField(blank=True, max_length=50, null=True)),
                ('amnt', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('taxable_amnt', models.FloatField(blank=True, null=True)),
                ('tax_amnt', models.FloatField(blank=True, null=True)),
                ('total_amnt', models.FloatField(blank=True, null=True)),
                ('sync_ird', models.IntegerField(blank=True, null=True)),
                ('billprt', models.IntegerField(blank=True, null=True)),
                ('billactive', models.IntegerField(blank=True, null=True)),
                ('bill_time', models.TimeField(auto_now=True, null=True)),
                ('billuser', models.CharField(blank=True, max_length=64, null=True)),
                ('is_realtime', models.BooleanField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='masterPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MergeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='User/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuinventory',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='menuinventory',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='printsts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='merged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='occHrs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='occMin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2]),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MenuInventory',
        ),
        migrations.AddField(
            model_name='mergetable',
            name='table1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table1', to='Restaurant.Table'),
        ),
        migrations.AddField(
            model_name='mergetable',
            name='table2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table2', to='Restaurant.Table'),
        ),
    ]
