# Generated by Django 3.0.2 on 2020-03-06 18:29

import Restaurant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now=True)),
                ('billnum', models.CharField(blank=True, max_length=50, null=True)),
                ('billuser', models.CharField(blank=True, max_length=64, null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='masterPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuinventory',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='menuinventory',
            name='menu',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='printsts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='occupied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[Restaurant.models.mycustomvalidator, Restaurant.models.val2]),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MenuInventory',
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Table'),
        ),
    ]
