# Generated by Django 3.0.2 on 2020-03-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20200307_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedby',
        ),
    ]
