# Generated by Django 3.0.4 on 2020-09-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_auto_20200507_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('activity', models.TextField(max_length=250)),
            ],
        ),
    ]
