# Generated by Django 3.0.2 on 2020-03-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_order_orderedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedby',
        ),
        migrations.RemoveField(
            model_name='order',
            name='printsts',
        ),
    ]
