# Generated by Django 3.0.2 on 2020-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_auto_20200307_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printsts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
