# Generated by Django 3.0.4 on 2020-12-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_auto_20201202_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
