# Generated by Django 3.0.2 on 2020-03-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_auto_20200307_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(upload_to='User/'),
        ),
    ]
