# Generated by Django 3.0.4 on 2020-12-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_profilepic_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
