# Generated by Django 3.0.2 on 2020-03-08 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_auto_20200308_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table1', to='Restaurant.Table')),
                ('table2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table2', to='Restaurant.Table')),
            ],
        ),
    ]
