# Generated by Django 3.0.4 on 2020-12-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_auto_20201207_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
