# Generated by Django 3.0.2 on 2020-03-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0014_mergetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='merged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
