# Generated by Django 3.0.4 on 2020-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0015_billno_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billnum',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
