# Generated by Django 3.1.4 on 2020-12-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0016_auto_20201213_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='servests',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='printsts',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
