# Generated by Django 3.0.2 on 2020-03-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0016_auto_20200308_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occupiedHour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mergetable',
            name='table2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table2', to='Restaurant.Table'),
        ),
    ]
