# Generated by Django 3.0.2 on 2020-03-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_auto_20200309_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='occupiedHour',
        ),
    ]
