# Generated by Django 3.1.4 on 2020-12-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_auto_20201226_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalServedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menu')),
            ],
        ),
    ]
