# Generated by Django 3.0.2 on 2020-03-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0018_remove_table_occupiedhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergetable',
            name='table1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table1', to='Restaurant.Table'),
        ),
    ]
