# Generated by Django 3.0.2 on 2020-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0019_auto_20200310_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occHrs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
