# Generated by Django 3.0.2 on 2020-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0020_table_occhrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='occMin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
