# Generated by Django 3.0.4 on 2020-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0021_table_occmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billactive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billprt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='fiscalyrs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_realtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sync_ird',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='taxable_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amnt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
