# Generated by Django 3.0.4 on 2020-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0022_auto_20200322_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_realtime',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
