# Generated by Django 3.0.4 on 2020-03-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0023_auto_20200322_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
